/** JS类型字面量枚举
 */
export declare enum ETYPE {
	arguments = 'arguments',
	array = 'array',
	arraybuffer = 'arraybuffer',
	boolean = 'boolean',
	date = 'date',
	dataview = 'dataview',
	error = 'error',
	float32array = 'float32array',
	float64array = 'float64array',
	function = 'function',
	int16array = 'int16array',
	int32array = 'int32array',
	int8array = 'int8array',
	map = 'map',
	number = 'number',
	object = 'object',
	regexp = 'regexp',
	set = 'set',
	string = 'string',
	symbol = 'symbol',
	uint16array = 'uint16array',
	uint32array = 'uint32array',
	uint8array = 'uint8array',
	uint8clampedarray = 'uint8clampedarray',
	weakmap = 'weakmap',
	weakref = 'weakref',
	weakset = 'weakset'
};
